// 'use client';
import "./global.css";
import Header from "../components/layout/header";
import { Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";
//import Sidebar from "@/components/layout/sidebar";
// import Footer from "@/components/layout/footer";
// import { useRouter } from "next/navigation";


const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

// export const metadata = {
//   title: "Skill Swap",
//   description: "Generated by Next.js",
// };



export default function RootLayout({ children }) {

  // const router = useRouter();
  // const pathsWithoutFooter = ["/add_post", "/add_skills", "/profile", "/userpage/[slug]"];

  // Check if the current path is included in the array
  // const showFooter = !pathsWithoutFooter.includes(router.pathname);
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <main className=" mx-auto">
        <Toaster position='top-center' reverseOrder={false} />
          {children}
          {/* {showFooter && <Footer />} */}
        </main>
      </body>
    </html>
  );
}
